package crypto

import (
	"context"
	"encoding/hex"
	"fmt"
	"os"
)

// EnvKeyProvider is the MVP implementation of KeyProvider.
// It reads the Key Encryption Key (KEK) from the DONAREC_KEK environment variable,
// which must be a hex-encoded 32-byte (256-bit) AES key.
//
// Security properties:
//   - KEK is never stored in source code, DB, or logs.
//   - KEK is read once at construction; the constructor errors if missing/invalid.
//   - WrapKey / UnwrapKey use AES-256-GCM (same as Encrypt/Decrypt) with the KEK.
//   - Each WrapKey call generates a fresh random nonce, so two wrappings of the same
//     DEK produce different ciphertext — this is safe because the wrappedDEK is stored
//     alongside its ciphertext and retrieved at decrypt time.
//
// Production upgrade path (D-26):
//
//	Replace with CloudKMSProvider that delegates to AWS KMS / GCP KMS / HashiCorp Vault.
//	The KeyProvider interface boundary means no call site changes are required.
//
// Anti-patterns guarded against (RESEARCH.md Pitfall 5):
//   - No hardcoded KEK literal in source code.
//   - Missing or malformed DONAREC_KEK fails at startup, not silently.
//   - KEK in env (not DB) so DB backups cannot reveal the KEK.
type EnvKeyProvider struct {
	kek []byte // 32-byte AES-256 key — never log or persist this value
}

// NewEnvKeyProvider constructs an EnvKeyProvider by reading DONAREC_KEK from env.
//
// Returns an error if:
//   - DONAREC_KEK is not set.
//   - DONAREC_KEK is not valid hex.
//   - DONAREC_KEK decodes to a byte slice that is not exactly 32 bytes.
func NewEnvKeyProvider() (*EnvKeyProvider, error) {
	kekHex := os.Getenv("DONAREC_KEK")
	if kekHex == "" {
		return nil, fmt.Errorf("DONAREC_KEK environment variable not set; " +
			"set it to a hex-encoded 32-byte AES-256 key before starting the server")
	}
	kek, err := hex.DecodeString(kekHex)
	if err != nil {
		return nil, fmt.Errorf("DONAREC_KEK is not valid hex: %w", err)
	}
	if len(kek) != 32 {
		return nil, fmt.Errorf("DONAREC_KEK must decode to exactly 32 bytes (got %d); "+
			"generate with: openssl rand -hex 32", len(kek))
	}
	return &EnvKeyProvider{kek: kek}, nil
}

// WrapKey encrypts a plaintext DEK using the KEK via AES-256-GCM.
// The output is suitable for storage alongside the field ciphertext.
//
// The plaintextDEK must be exactly 32 bytes (generated by EncryptField).
// The wrapped DEK is GCM-authenticated: tampering is detected on UnwrapKey.
func (e *EnvKeyProvider) WrapKey(_ context.Context, plaintextDEK []byte) ([]byte, error) {
	wrapped, err := Encrypt(e.kek, plaintextDEK)
	if err != nil {
		return nil, fmt.Errorf("WrapKey: %w", err)
	}
	return wrapped, nil
}

// UnwrapKey decrypts a wrapped DEK using the KEK via AES-256-GCM.
// Returns the plaintext DEK for a single decrypt operation.
//
// The caller must use the DEK immediately and must not persist or log it.
// Zero the DEK from memory after use if your threat model requires it
// (Go's GC does not guarantee timely zeroing; this is an accepted risk for MVP).
func (e *EnvKeyProvider) UnwrapKey(_ context.Context, wrappedDEK []byte) ([]byte, error) {
	dek, err := Decrypt(e.kek, wrappedDEK)
	if err != nil {
		return nil, fmt.Errorf("UnwrapKey: %w", err)
	}
	return dek, nil
}
